//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyPhongKhamNhi
{
    using System;
    using System.Collections.Generic;
    
    public partial class NhanVien
    {
        public string maNV { get; set; }
        public string hoTenNV { get; set; }
        public Nullable<System.DateTime> ngaySinh { get; set; }
        public Nullable<int> namLamViec { get; set; }
        public string gioiTinh { get; set; }
        public Nullable<int> luong { get; set; }
        public string maPB { get; set; }
    
        public virtual PhongBan PhongBan { get; set; }
    }
}
