//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyPhongKhamNhi
{
    using System;
    using System.Collections.Generic;
    
    public partial class PhongBan
    {
        public PhongBan()
        {
            this.NhanVien = new HashSet<NhanVien>();
        }
    
        public string maPB { get; set; }
        public string tenPB { get; set; }
        public string emailPB { get; set; }
        public string dienThoai { get; set; }
    
        public virtual ICollection<NhanVien> NhanVien { get; set; }
    }
}
